name: cargo-bloat

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: cargo build

    - name: Build without regex
      run: cargo build --no-default-features
